### PR TITLE
[PLUGIN]: JacLang FastAPI Initial Implementation

### PR DESCRIPTION
**Pull request by amadolid**
# **Recommended Usage**
```python
import:py from jaclang_fastapi, FastAPI, start;

walker post_no_body {}
walker post_with_body {
    has a: str;
}

walker get_no_body {
    obj Specs {
        static has methods: list = ["get"];
    }
}

walker get_with_query {
    # @query - future improvements instead of adding manually on as_query
    has a: str;

    obj Specs {
        static has methods: list = ["get"], as_query: list = ["a"];
    }
}

walker get_all_query {
    # @query - future improvements instead of adding manually on as_query
    has a: str;
    has b: str;

    obj Specs {
        static has methods: list = ["get"], as_query: list = "*";
    }
}

walker combination {
    has a: str;
    has b: str;
    has c: str;

    obj Specs {
        static has methods: list = ["post", "get"], as_query: list = ["a", "b"];
    }
}

walker post_path_var {
    has a: str;

    obj Specs {
        static has path: str = "/{a}", methods: list = ["post", "get"];
    }
}

walker combination2 {
    has a: str;
    has b: str;
    has c: str;

    obj Specs {
        static has path: str = "/{a}", methods: list = ["post", "get"], as_query: list = ["b"];
    }
}

with entry:__main__ {
    start(
        host="0.0.0.0",
        port=8000
    );
}
```
# via **Decorator**
```python
import:py from jaclang_fastapi, FastAPI, specs, start;

walker post_no_body {}
walker post_with_body {
    has a: str;
}

@specs(methods=["get"])
walker get_no_body {}

@specs(methods=["get"], as_query=["a"])
walker get_with_query {
    # @query - future improvements instead of adding manually on as_query
    has a: str;
}

@specs(methods=["get"], as_query="*")
walker get_all_query {
    # @query - future improvements instead of adding manually on as_query
    has a: str;
    has b: str;
}

@specs(methods=["post", "get"], as_query=["a", "b"])
walker combination {
    has a: str;
    has b: str;
    has c: str;
}

@specs(path = "/{a}", methods=["post"])
walker post_path_var {
    has a: str;
}

@specs(path = "/{a}", methods=["post", "get"], as_query=["b"])
walker combination2 {
    has a: str;
    has b: str;
    has c: str;
}

with entry:__main__ {
    start(
        host="0.0.0.0",
        port=8000
    );
}
```
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by marsninja** [comment]
Btw @amadolid  I'll be bringing in info on has variables including access visibility into the architype class from the make_* plugin interface. That will be heat for the as_query improvement idea. Feel free to make an issue for it btw.

**Comment by ypkang** [comment]
/user/login gives this warning
```
WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/yipingkang/projects/jaclang/fastapi/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
```

**Comment by ypkang** [comment]
Need to `pip install tomli`. We should add that to the setup.py

**Comment by ypkang** [comment]
request to /user/login gives this warining

```
WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/yipingkang/projects/myca-buddy/venv2/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

**Comment by amadolid** [comment]
moved to https://github.com/Jaseci-Labs/jaclang-jaseci/pull/1

**Pull request closed without merging**
